<a href="https://colab.research.google.com/github/Raji-13/healthcare-chatbot/blob/master/AI_MEDICAL_CHATBOT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tkinter as Tk

In [ ]:
!apt-get install swig cmake libopenmpi-dev zlib1g-dev xvfb x11-utils ghostscript ffmpeg -qq #remove -qq for full output
!pip install pyvirtualdisplay ghostscript

Selecting previously unselected package fonts-droid-fallback.
(Reading database ... 128126 files and directories currently installed.)
Preparing to unpack .../00-fonts-droid-fallback_1%3a6.0.1r16-1.1_all.deb ...
Unpacking fonts-droid-fallback (1:6.0.1r16-1.1) ...
Selecting previously unselected package poppler-data.
Preparing to unpack .../01-poppler-data_0.4.9-2_all.deb ...
Unpacking poppler-data (0.4.9-2) ...
Selecting previously unselected package fonts-noto-mono.
Preparing to unpack .../02-fonts-noto-mono_20200323-1build1~ubuntu20.04.1_all.deb ...
Unpacking fonts-noto-mono (20200323-1build1~ubuntu20.04.1) ...
Selecting previously unselected package fonts-urw-base35.
Preparing to unpack .../03-fonts-urw-base35_20170801.1-3_all.deb ...
Unpacking fonts-urw-base35 (20170801.1-3) ...
Selecting previously unselected package libgs9-common.
Preparing to unpack .../04-libgs9-common_9.50~dfsg-5ubuntu4.6_all.deb ...
Unpacking libgs9-common (9.50~dfsg-5ubuntu4.6) ...
Selecting previously unsel

In [ ]:
import os
os.system("Xvfb :1 -screen 0 1024x768x24 &")
os.environ['DISPLAY'] = ':1'
from tkinter import *
from google.colab.patches import cv2_imshow
from google.colab import output
from PIL import Image

In [ ]:
from tkinter import * 
import os

In [ ]:
from matplotlib.pyplot import *
from matplotlib.widgets import *
from math import *
from random import *
from numpy import *
from tkinter import *

In [ ]:
def destroyPackWidget(parent):
  for e in parent.pack_slaves():
    e.destroy()
def register():
  global root,register_screen
  destroyPackWidget(root)
  register_screen=root
#    register_screen = Toplevel(main_screen)
  register_screen.title("Register")
  register_screen.geometry("300x250")
  global username
  global password
  global username_entry
  global password_entry
  username = StringVar()
  password = StringVar()
  Label(register_screen, text="Please enter the details below", bg="blue").pack()
  Label(register_screen, text="").pack()
  username_lable = Label(register_screen, text="Username * ")
  username_lable.pack()
  username_entry = Entry(register_screen, textvariable=username)
  username_entry.pack()
  password_lable = Label(register_screen, text="Password * ")
  password_lable.pack()
  password_entry = Entry(register_screen, textvariable=password, show='*')
  password_entry.pack()
  Label(register_screen, text="").pack()
  Button(register_screen, text="Register", width=10, height=1, bg="blue", command=register_user).pack()



In [ ]:
def login():
  global login_screen
  login_screen = Toplevel(main_screen)
  login_screen.title("Login")
  login_screen.geometry("300x250")
  Label(login_screen, text="Please enter details below to login").pack()
  Label(login_screen, text="").pack()
  global username_verify
  global password_verify
  username_verify = StringVar()
  password_verify = StringVar()
  global username_login_entry
  global password_login_entry
  Label(login_screen, text="Username * ").pack()
  username_login_entry = Entry(login_screen, textvariable=username_verify)
  username_login_entry.pack()
  Label(login_screen, text="").pack()
  Label(login_screen, text="Password * ").pack()
  password_login_entry = Entry(login_screen, textvariable=password_verify, show='*')
  password_login_entry.pack()
  Label(login_screen, text="").pack()
  Button(login_screen, text="Login", width=10, height=1, command=login_verify).pack()

In [ ]:
def btnSucess_Click():
  global root
  destroyPackWidget(root)
def register_user():
  global root,username,password
  username_info = username.get()
  password_info = password.get()
  print("abc",username_info,password_info,"xyz")
  file = open(username_info, "w")
  file.write(username_info + "\n")
  file.write(password_info)
  file.close()
  username_entry.delete(0, END)
  password_entry.delete(0, END)
  Label(root, text="Registration Success", fg="green", font=("calibri", 11)).pack()
  Button(root,text="Click Here to proceed",command=btnSucess_Click).pack()

In [ ]:
def login_verify():
  username1 = username_verify.get()
  password1 = password_verify.get()
  username_login_entry.delete(0, END)
  password_login_entry.delete(0, END)
  list_of_files = os.listdir()
  if username1 in list_of_files:
    file1 = open(username1, "r")
    verify = file1.read().splitlines()
    if password1 in verify:
      login_sucess()
    else:
      password_not_recognised()
  else:
    user_not_found()

In [ ]:
def login_sucess():
  global login_success_screen
  login_success_screen = Toplevel(login_screen)
  login_success_screen.title("Success")
  login_success_screen.geometry("150x100")
  Label(login_success_screen, text="Login Success").pack()
  Button(login_success_screen, text="OK", command=delete_login_success).pack()

In [ ]:
def password_not_recognised():
  global password_not_recog_screen
  password_not_recog_screen = Toplevel(login_screen)
  password_not_recog_screen.title("Success")
  password_not_recog_screen.geometry("150x100")
  Label(password_not_recog_screen, text="Invalid Password ").pack()
  Button(password_not_recog_screen, text="OK", command=delete_password_not_recognised).pack()


In [ ]:
def user_not_found():
  global user_not_found_screen
  user_not_found_screen = Toplevel(login_screen)
  user_not_found_screen.title("Success")
  user_not_found_screen.geometry("150x100")
  Label(user_not_found_screen, text="User Not Found").pack()
  Button(user_not_found_screen, text="OK", command=delete_user_not_found_screen).pack()

In [ ]:
def delete_login_success():
  login_success_screen.destroy()

In [ ]:
def delete_password_not_recognised():
  password_not_recog_screen.destroy()

In [ ]:
def delete_user_not_found_screen():
  user_not_found_screen.destroy()
def main_account_screen(frmmain):
  main_screen=frmmain
  main_screen.geometry("300x250")
  main_screen.title("Account Login")
  Label(main_screen,text="Select Your Choice", bg="blue", width="300", height="2", font=("Calibri", 13)).pack()
  Label(main_screen,text="").pack()
  Button(main_screen,text="Login", height="2", width="30", command=login).pack()
  Label(main_screen,text="").pack()
  Button(main_screen,text="Register", height="2", width="30", command=register).pack()
root = Tk()
main_account_screen(root)
root.mainloop()


TypeError: ignored

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
training_dataset = pd.read_csv('/content/drive/MyDrive/SELF DIAGNOSIS MEDICAL CHATBOT/Training.csv')
test_dataset = pd.read_csv('/content/drive/MyDrive/SELF DIAGNOSIS MEDICAL CHATBOT/Testing.csv')

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [5]:
X = training_dataset.iloc[:, 0:132].values
print(X)
y = training_dataset.iloc[:, -1].values
print(y)


[[1 1 1 ... 0 0 0]
 [0 1 1 ... 0 0 0]
 [1 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 1 0 ... 1 1 1]]
['Fungal infection' 'Fungal infection' 'Fungal infection' ...
 'Urinary tract infection' 'Psoriasis' 'Impetigo']


In [6]:
dimensionality_reduction = training_dataset.groupby(training_dataset['prognosis']).max()
#print(dimensionality_reduction)

In [7]:
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
y = labelencoder.fit_transform(y)
print(y)

[15 15 15 ... 38 35 27]


In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [9]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier()
classifier.fit(X_train, y_train)

DecisionTreeClassifier()

In [10]:
cols     = training_dataset.columns
cols     = cols[:-1]

In [11]:
importances = classifier.feature_importances_
indices = np.argsort(importances)[::-1]
features = cols

In [12]:
from sklearn.tree import _tree

In [16]:
def execute_bot():
  #print("Please reply with yes/Yes or no/No for the following symptoms") 
  def print_disease(node):
    print(node)
    node = node[0]
    print(len(node))
    val  = node.nonzero() 
    print(val)
    disease = labelencoder.inverse_transform(val[0])
    return disease
  def tree_to_code(tree, feature_names):
    tree_ = tree.tree_
    print(tree_)
    feature_name = [
        feature_names[i] if i != _tree.TREE_UNDEFINED else "undefined!"
        for i in tree_.feature
    ]
    print("def tree({}):".format(", ".join(feature_names)))
    symptoms_present = []
    def recurse(node, depth):
      indent = "  " * depth
      if tree_.feature[node] != _tree.TREE_UNDEFINED:
        name = feature_name[node]
        threshold = tree_.threshold[node]
        #print("threshold")
        print(name + " ?")
        ans = input()
        ans = ans.lower()
        if ans == 'yes':
          val = 1
        else:
          val = 0
        if  val <= threshold:
          recurse(tree_.children_left[node], depth + 1)
        else:
          symptoms_present.append(name)
          recurse(tree_.children_right[node], depth + 1)
      else:
        present_disease = print_disease(tree_.value[node])
        print( "You may have " +  present_disease )
        print()
        red_cols = dimensionality_reduction.columns 
        symptoms_given = red_cols[dimensionality_reduction.loc[present_disease].values[0].nonzero()]
        print("symptoms present  " + str(list(symptoms_present)))
        print()
        print("symptoms given "  +  str(list(symptoms_given)) )  
        print()
        confidence_level = (1.0*len(symptoms_present))/len(symptoms_given)
        print("confidence level is " + str(confidence_level))
        print()
        print('The model suggests:')
        print()
        row = doctors[doctors['disease'] == present_disease[0]]
        #print('Consult ', str(row['name'].values))
        print()
        print('Visit ', str(row['link'].values))
        #print(present_disease[0])
    recurse(0, 1)
  tree_to_code(classifier,cols)
doc_dataset = pd.read_csv('/content/drive/MyDrive/SELF DIAGNOSIS MEDICAL CHATBOT/doctors_dataset.htm', names = ['Name', 'Description'])
diseases = dimensionality_reduction.index
diseases = pd.DataFrame(diseases)

doctors = pd.DataFrame()
doctors['name'] = np.nan
doctors['link'] = np.nan
doctors['disease'] = np.nan

doctors['disease'] = diseases['prognosis']


doctors['name'] = doc_dataset['Name']
doctors['link'] = doc_dataset['Description']

record = doctors[doctors['disease'] == 'AIDS']
record['name']
record['link']




# Execute the bot and see it in Action
execute_bot()
  





                

def tree(itching, skin_rash, nodal_skin_eruptions, continuous_sneezing, shivering, chills, joint_pain, stomach_pain, acidity, ulcers_on_tongue, muscle_wasting, vomiting, burning_micturition, spotting_ urination, fatigue, weight_gain, anxiety, cold_hands_and_feets, mood_swings, weight_loss, restlessness, lethargy, patches_in_throat, irregular_sugar_level, cough, high_fever, sunken_eyes, breathlessness, sweating, dehydration, indigestion, headache, yellowish_skin, dark_urine, nausea, loss_of_appetite, pain_behind_the_eyes, back_pain, constipation, abdominal_pain, diarrhoea, mild_fever, yellow_urine, yellowing_of_eyes, acute_liver_failure, fluid_overload, swelling_of_stomach, swelled_lymph_nodes, malaise, blurred_and_distorted_vision, phlegm, throat_irritation, redness_of_eyes, sinus_pressure, runny_nose, congestion, chest_pain, weakness_in_limbs, fast_heart_rate, pain_during_bowel_movements, pain_in_anal_region, bloody_stool, irritation_in_anus, neck_pain, dizziness, cramps, bruising, ob

# New Section

NameError: ignored